Develop
mate-academy/js_invert-color pull request #102
Opened 2020-05-21 21:30 UTC by V2473

2020-05-24 13:15 UTC, ivanchuk-yurii requested changes

2020-05-24 13:15 UTC, wa7er14 commented on src/invertColor.js
> +  }
якщо присвоюєш значення, краще робити через тренарний ? :

2020-05-26 09:36 UTC, ivanchuk-yurii requested changes

2020-05-26 09:36 UTC, wa7er14 commented on src/invertColor.js
> +      : invert += invertCurColor;
```suggestion
   invert += invertCurColor.length < 2 ? '0' + invertCurColor : invertCurColor;
```

2020-05-26 16:23 UTC, danheim approved these changes
lgtm

2025-07-18 15:04 UTC, closed without merging